### ISSUE TITLE
启动总是报java.lang.IllegalStateException: No instances found of configserver (server-config)

### ISSUE THREAD

**Issue by fanyiqiang2015** [yonyou-auto-dev/microservice-ops#12]
1.这个是不是用了serverConfig做配置文件统一管理？
2.能不能写一安装布置文档

**Comment by ambluse** [comment]
需要的 readme中的图蓝色部分有提到是另外一个项目 https://github.com/yonyou-auto-dev/microservice-server  需要部署config-server
